apiVersion: apps/v1
kind: Deployment
metadata:
  name: cycle-deployment
  labels:
    app: cycle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cycle
  template:
    metadata:
      labels:
        app: cycle
    spec:
      containers:
      - name: cycle-container
        image: shaikmustafa/game
        ports:
        - containerPort: 80
